// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCr7V6338QPFocexsh80QJsx2KGlsHnIM',
    appId: '1:542761411437:web:b73ab8658ef4cc87e67064',
    messagingSenderId: '542761411437',
    projectId: 'beebuzz-cc84e',
    authDomain: 'beebuzz-cc84e.firebaseapp.com',
    storageBucket: 'beebuzz-cc84e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH2lt2EF7sY2X72jPg0PUD19H34pD0QEw',
    appId: '1:542761411437:android:fd2b6a7f7801f7a4e67064',
    messagingSenderId: '542761411437',
    projectId: 'beebuzz-cc84e',
    storageBucket: 'beebuzz-cc84e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGPBA_ZjAOOGjbI4M3JXpIm_aOJwVaN0A',
    appId: '1:542761411437:ios:1045583be3a4b612e67064',
    messagingSenderId: '542761411437',
    projectId: 'beebuzz-cc84e',
    storageBucket: 'beebuzz-cc84e.appspot.com',
    androidClientId: '542761411437-j64ubpmjoaat6necc3blv2ca3c1f5ulh.apps.googleusercontent.com',
    iosClientId: '542761411437-33fteq61m3l05t8i8k83doct4p0ncjkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.beebuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGPBA_ZjAOOGjbI4M3JXpIm_aOJwVaN0A',
    appId: '1:542761411437:ios:3fba8bdac73ab8d9e67064',
    messagingSenderId: '542761411437',
    projectId: 'beebuzz-cc84e',
    storageBucket: 'beebuzz-cc84e.appspot.com',
    androidClientId: '542761411437-j64ubpmjoaat6necc3blv2ca3c1f5ulh.apps.googleusercontent.com',
    iosClientId: '542761411437-ie9ril71q8p5eu2p2s4noo8ahvau0fln.apps.googleusercontent.com',
    iosBundleId: 'com.example.beebuzz.RunnerTests',
  );
}
